### ISSUE TITLE
Abilty to toggle mending from villager trades

### ISSUE THREAD

**Issue by PurrfectMIstake** [YouHaveTrouble/BalanceBringer#3]
Could you please add: Abilty to toggle mending from villager trades entirely and modify mending value multiplier? eg: 0.5 = half.

You also mentioned that you use Purpur, I also do.
Do you plan on updating this to fit purpur and uploading it somewhere? I'd love the link because I'd love this plugin.

**Comment by iamcion** [comment]
> > Abilty to toggle mending from villager trades entirely
> 
> I believe that would be possible
> 
> > modify mending value multiplier? eg: 0.5 = half
> 
> Not really sure what you mean here, ellaborate please
> 
> > > I mean, it would be nice to have a feature where we can modify the multiplier of mendings capabilities. For example 0.5 = 50% less repairs go back into the items for the same amount of xp as it normally would (1.0). Someone could also increase it if they really want.

- Refer to this plugin as an example.
https://github.com/NoniDOTio/SMPtweaks/tree/master/src/main/java/io/noni/smptweaks/events

**Comment by YouHaveTrouble** [comment]
ah, so basically mending modifier

**Comment by iamcion** [comment]
> ah, so basically mending modifier

yes.
